### ISSUE TITLE
`Invalid field selection bucket` when accessing public bucket with java-storage-nio

### ISSUE THREAD

**Issue by asm0dey** [googleapis/java-storage-nio#328]
Thanks for stopping by to let us know something could be better!

If you are still having issues, please include as much information as possible:

#### Environment details

1. Google Cloud Storage
2. OS type and version: `Linux UNIT-1793 5.8.18-1-MANJARO #1 SMP PREEMPT Sun Nov 1 14:10:04 UTC 2020 x86_64 GNU/Linux`
3. Java version: OpenJDK 11
4. storage_nio version(s): 0.122.3

#### Steps to reproduce

I'm trying to access public bucket with storage nio

#### Code example

```kotlin
  private val httpTransport by lazy { ApacheHttpTransport() }
  private val fs: CloudStorageFileSystem by lazy {
    val gcsTransportOptions = HttpTransportOptions
      .newBuilder()
      .setHttpTransportFactory { httpTransport }
      .build()

    val creds =
      settingsPath?.let { GoogleCredentials.fromStream(BufferedInputStream(FileInputStream(it))) } ?:
      NoCredentials.getInstance()

    val storageOptions = StorageOptions
      .newBuilder()
      .setCredentials(creds)
      .setTransportOptions(gcsTransportOptions)
      .build()
    CloudStorageFileSystem.forBucket(bucket, CloudStorageConfiguration.builder().permitEmptyPathComponents(true).build(), storageOptions)
  }

// snip
Files.exists(fs.getPath(absolutePath))
//snip
```

#### Stack trace
```
2020-12-22 13:42:07,471 [  20051]   WARN - ols.rfs.driver.LogErrorHandler - com.jetbrains.bigdatatools.rfs.driver.DriverRequestException: Exception during driver request: com.google.cloud.storage.StorageException: Invalid field selection bucket
	at com.jetbrains.bigdatatools.rfs.driver.SafeExecutor$TimeoutExecutor.execute(SafeExecutor.kt:76)
	at com.jetbrains.bigdatatools.rfs.driver.SafeExecutor$TimeoutExecutor.execute$default(SafeExecutor.kt:63)
	at com.jetbrains.bigdatatools.rfs.driver.SafeExecutor$TimeoutExecutor.strictExecute(SafeExecutor.kt:57)
	at com.jetbrains.bigdatatools.rfs.driver.SafeExecutor.executeWithTimeOut(SafeExecutor.kt:104)
	at com.jetbrains.bigdatatools.rfs.driver.SafeExecutor.access$executeWithTimeOut(SafeExecutor.kt:11)
	at com.jetbrains.bigdatatools.rfs.driver.SafeExecutor$safeExecute$1.invoke(SafeExecutor.kt:111)
	at com.jetbrains.bigdatatools.rfs.driver.DriverErrorHandler$DefaultImpls.withErrorHandling(DriverErrorHandler.kt:15)
	at com.jetbrains.bigdatatools.rfs.driver.CompositeDriverErrorHandler.withErrorHandling(DriverErrorHandler.kt:25)
	at com.jetbrains.bigdatatools.rfs.driver.SafeExecutor.safeExecute(SafeExecutor.kt:110)
	at com.jetbrains.bigdatatools.rfs.driver.DriverBase.safeExecute(DriverBase.kt:136)
	at com.jetbrains.bigdatatools.rfs.driver.DriverBase.safeExecute$default(DriverBase.kt:133)
	at com.jetbrains.bigdatatools.rfs.driver.DriverBase.listStatus(DriverBase.kt:61)
	at com.jetbrains.bigdatatools.rfs.projectview.nodes.RfsCachedChildrenNode.getChildren(RfsCachedChildrenNode.kt:175)
	at com.jetbrains.bigdatatools.rfs.projectview.nodes.RfsMountNode.calculateChildren(RfsMountNode.kt:15)
	at com.jetbrains.bigdatatools.rfs.projectview.nodes.RfsCachedChildrenNode$scheduleChildrenRecalculation$2.invoke(RfsCachedChildrenNode.kt:113)
	at com.jetbrains.bigdatatools.rfs.projectview.nodes.RfsCachedChildrenNode$scheduleChildrenRecalculation$2.invoke(RfsCachedChildrenNode.kt:19)
	at com.jetbrains.bigdatatools.util.ThreadUtilsKt$executeOnPooledThread$1.run(ThreadUtils.kt:24)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.cloud.storage.StorageException: Invalid field selection bucket
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:231)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.get(HttpStorageRpc.java:456)
	at com.google.cloud.storage.StorageImpl$5.call(StorageImpl.java:324)
	at com.google.cloud.storage.StorageImpl$5.call(StorageImpl.java:321)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:320)
	at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.checkAccess(CloudStorageFileSystemProvider.java:736)
	at java.base/java.nio.file.Files.exists(Files.java:2514)
	at com.intellij.util.io.PathKt.exists(path.kt:19)
	at org.jetbrains.hdfsplugin.hdfs.drivers.gcs.GCSDriver.doListStatus(GCSDriver.kt:79)
	at com.jetbrains.bigdatatools.rfs.driver.DriverBase$listStatus$1.invoke(DriverBase.kt:63)
	at com.jetbrains.bigdatatools.rfs.driver.DriverBase$listStatus$1.invoke(DriverBase.kt:9)
	at com.jetbrains.bigdatatools.rfs.driver.SafeExecutor$safeExecute$1$1.invoke(SafeExecutor.kt:112)
	at com.jetbrains.bigdatatools.rfs.driver.SafeExecutor$TimeoutExecutor.updateValue(SafeExecutor.kt:50)
	at com.jetbrains.bigdatatools.rfs.driver.SafeExecutor$TimeoutExecutor$withInterrupt$future$1.run(SafeExecutor.kt:85)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	... 5 more
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
GET https://storage.googleapis.com/storage/v1/b/gcp-public-data-landsat/o/?fields=bucket,name,id&projection=full
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "location" : "fields",
    "locationType" : "parameter",
    "message" : "Invalid field selection bucket",
    "reason" : "invalidParameter"
  } ],
  "message" : "Invalid field selection bucket"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:149)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:112)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:39)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:443)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1108)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:541)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:474)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:591)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.get(HttpStorageRpc.java:453)
	... 21 more
```

**Comment by suraj-qlogic** [comment]
@asm0dey ,Thanks for filling issue.I am not able to reproduced this issue in **java** as well as in **kotlin**.

Would you try below step and Please let us know if this helps you?

**Sample Code**
```java
package com.gcp.storage_nio

import android.content.ContentValues
import android.os.Bundle
import android.os.StrictMode
import android.util.Log
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.Button
import androidx.fragment.app.Fragment
import com.google.api.client.http.apache.ApacheHttpTransport
import com.google.auth.oauth2.GoogleCredentials
import com.google.cloud.http.HttpTransportOptions
import com.google.cloud.storage.StorageOptions
import com.google.cloud.storage.contrib.nio.CloudStorageConfiguration
import com.google.cloud.storage.contrib.nio.CloudStorageFileSystem
import java.io.BufferedInputStream
import java.nio.file.Files


class FirstFragment : Fragment() {

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        // Inflate the layout for this fragment
        return inflater.inflate(R.layout.fragment_first, container, false)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        val policy = StrictMode.ThreadPolicy.Builder().permitAll().build()
        StrictMode.setThreadPolicy(policy)
        view.findViewById<Button>(R.id.button_first).setOnClickListener {
            val httpTransport by lazy { ApacheHttpTransport() }
            val fs: CloudStorageFileSystem by lazy {
                val gcsTransportOptions = HttpTransportOptions
                    .newBuilder()
                    .setHttpTransportFactory { httpTransport }
                    .build()


                val creds =GoogleCredentials.fromStream(
                    BufferedInputStream(
                        resources.openRawResource(
                            R.raw.credentials //load credentials from raw resources,put credentials.json inside raw folder
                        )
                    )
                );

                val bucket ="gcp-public-data-landsat";
                val storageOptions = StorageOptions
                    .newBuilder()
                    .setCredentials(creds)
                    .setTransportOptions(gcsTransportOptions)
                    .build()
                CloudStorageFileSystem.forBucket(
                    bucket, CloudStorageConfiguration.builder().permitEmptyPathComponents(
                        true
                    ).build(), storageOptions
                )
            }
            Log.d(ContentValues.TAG, "Bucket::${fs.bucket()}")
            val absolutePath="LC08/01_\$folder\$"
            val response=Files.exists(fs.getPath(absolutePath))
            Log.d(ContentValues.TAG, "Response value::$response")
        }
    }
}
```
**Output**
```
D/ContentValues: Bucket::gcp-public-data-landsat
D/ContentValues: Response value::true
```

**Comment by asm0dey** [comment]
Hi @suraj-qlogic, thank you for idea. As far as I can see this is a snippet for android. Do you have similar sippet for desktop/CI Java/Kotlin?

**Comment by asm0dey** [comment]
Also, your snippet is for private bucket and I've been writing about public one

**Comment by suraj-qlogic** [comment]
> Also, your snippet is for private bucket and I've been writing about public one

In snippet i was used public bucket ```gcp-public-data-landsat```.

**Comment by asm0dey** [comment]
Sorry, I was wrong, but why your snippet uses credentials then? I believe we don't need credentials to access public buckets?

**Comment by suraj-qlogic** [comment]
> Sorry, I was wrong, but why your snippet uses credentials then? I believe we don't need credentials to access public buckets?

Yes,There is no credentials is required for access public bucket.Below line also work.
```java
 val creds=NoCredentials.getInstance();
```

**Comment by asm0dey** [comment]
@suraj-qlogic thank you for the hint, works for me in a clean environment. That means it's something inside our environment and not the bug in `java-storage-nio`.

Thank you for your help, you're free to close this bugreport.

Also, I would appreciate any ideas on what may interfere into the work of client.

**Comment by asm0dey** [comment]
I managed to reproduce the error!

Please, consider following snippet:

```kotlin
import com.google.api.client.http.apache.ApacheHttpTransport
import com.google.cloud.NoCredentials
import com.google.cloud.http.HttpTransportOptions
import com.google.cloud.storage.StorageOptions
import com.google.cloud.storage.contrib.nio.CloudStorageConfiguration
import com.google.cloud.storage.contrib.nio.CloudStorageFileSystem
import java.nio.file.Files

val httpTransport by lazy { ApacheHttpTransport() }
val fs: CloudStorageFileSystem by lazy {
    val gcsTransportOptions = HttpTransportOptions
        .newBuilder()
        .setHttpTransportFactory { httpTransport }
        .build()


    val creds= NoCredentials.getInstance()

    val bucket = "gcp-public-data-landsat";
    val storageOptions = StorageOptions
        .newBuilder()
        .setCredentials(creds)
        .setTransportOptions(gcsTransportOptions)
        .build()
    CloudStorageFileSystem.forBucket(
        bucket, CloudStorageConfiguration.builder().permitEmptyPathComponents(
            true
        ).stripPrefixSlash(false).build(), storageOptions
    )
}
println("Bucket::${fs.bucket()}")
val absolutePath = "LC08/01_\$folder\$"
val response = Files.exists(fs.getPath(absolutePath))
println("Response value::$response")
```

**Comment by suraj-qlogic** [comment]
@asm0dey ,Sorry for a delay in reply.I have executed above code so many times, but I am unable to reproduce this bug. Would you please share a [method](https://github.com/googleapis/java-storage-nio/blob/2e18dda977b044cf77aeef3ddb0ec63bfbd21fa5/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java#L736) parameter value before making a rpc call?

```java 
storage.get(cloudPath.getBlobId(), Storage.BlobGetOption.fields(Storage.BlobField.ID))
```
In Following format.
``` java
cloudPath.getBlobId()=>BlobId{bucket=xyz, name=abc, generation=null}
Storage.BlobGetOption.fields(Storage.BlobField.ID)=>BlobGetOption{name=fields, value=bucket,name,id}
```

**Comment by shaffeeullah** [comment]
Closing due to inactivity. Please re-open with the requested information if this is still an issue.
