### ISSUE TITLE
Make serviceusage.services.use permission optional

### ISSUE THREAD

**Issue by iura1981** [googleapis/java-storage-nio#61]
**Is your feature request related to a problem? Please describe.**
Right now following permission serviceusage.services.use is a must when for example I call Files.move(source, target) on my own bucket (I use default setting and not use Requester Pay feature). it means that even having default Storage Admin roles is not enough,
without that permission I got following error (and source blob is not removed!):
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "bvb-testing-media-strategy@tacitknowledge-automation-lab.iam.gserviceaccount.com does not have serviceusage.services.use access to project 1020839626458.",
    "reason" : "forbidden"
  } ],
  "message" : "bvb-testing-media-strategy@tacitknowledge-automation-lab.iam.gserviceaccount.com does not have serviceusage.services.use access to project 1020839626458."
}

at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:229)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.list(HttpStorageRpc.java:370)
	at com.google.cloud.storage.StorageImpl$8.call(StorageImpl.java:376)
	at com.google.cloud.storage.StorageImpl$8.call(StorageImpl.java:373)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.storage.StorageImpl.listBlobs(StorageImpl.java:372)
	at com.google.cloud.storage.StorageImpl.list(StorageImpl.java:328)
	at com.google.cloud.storage.contrib.nio.CloudStoragePath.seemsLikeADirectoryAndUsePseudoDirectories(CloudStoragePath.java:107)
	at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.deleteIfExists(CloudStorageFileSystemProvider.java:497)
	at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.delete(CloudStorageFileSystemProvider.java:533)
	at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.move(CloudStorageFileSystemProvider.java:550)
	at java.nio.file.Files.move(Files.java:1395)
	at com.tk.nio.gs.GSFileSystemTest.moveFileToArchive(GSFileSystemTest.java:52)
	at com.tk.nio.gs.GSFileSystemTest.main(GSFileSystemTest.java:33)
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
 
This happens it following part of the code:
com.google.cloud.storage.contrib.nio.CloudStoragePath:

Page<Blob> list =
        storage.list(
            this.bucket(),
            Storage.BlobListOption.prefix(prefix),
            // we only look at the first result, so no need for a bigger page.
            Storage.BlobListOption.pageSize(1),
            fileSystem.provider().getProject() == null
                ? null
                : Storage.BlobListOption.userProject(fileSystem.provider().getProject()));

So when you pass projectId - a check for billing which requires mentioned permission is performed.

**Describe the solution you'd like**
Provide a setting which allows to not pass projectId - so serviceusage.services.use permission will not be required.

**Comment by frankyn** [comment]
Hi @iura1981,

Thanks for filing this issue, I'm classifying it as a question for now.

IIUC the repro code is:

```java
Page list =
storage.list(
this.bucket(),
Storage.BlobListOption.prefix(prefix),
// we only look at the first result, so no need for a bigger page.
Storage.BlobListOption.pageSize(1),
fileSystem.provider().getProject() == null
? null
: Storage.BlobListOption.userProject(fileSystem.provider().getProject()));
```

Why not instead remove `,
fileSystem.provider().getProject() == null
? null
: Storage.BlobListOption.userProject(fileSystem.provider().getProject())`?

**Comment by frankyn** [comment]
Hi @iura1981, checking in if you're still experiencing this issue.
