### ISSUE TITLE
Authenticate using OAuth2 access token 

### ISSUE THREAD

**Issue by wayglem** [googleapis/java-storage-nio#614]
Hi,
I use a user access token with the storage API directly, however I'm stuck because there is no way to download a chunk of file.
```
        Credentials credentials = GoogleCredentials.create(new AccessToken(accessToken, expirationTime));
        Storage storage = StorageOptions.newBuilder()
                .setCredentials(credentials)
                .build()
                .getService();
```
I discovered this API by this SO thread https://stackoverflow.com/questions/56636943/downloading-an-object-byte-range-from-google-cloud-storage-using-java-sdk. Is there anyway to pass the credentials?

**Comment by Breathtender** [comment]
I'm not sure I'm fully understanding your issue. Does the code you presented above not work?
If that does work, I would imagine that doing that in accord with the proposed solution from Stackoverflow, should work to solve your issue?

But perhaps I'm missing something, could you help me understand a bit more what it is you're trying to do and what issue you are running into?

**Comment by wayglem** [comment]
Sorry I was indeed not very clear.

The code I posted is the way I authenticate users using the google-cloud-storage java client.

I wanted to do something similar with java-storage-nio but I don't see how I could pass the access token. Here is the code that I tried
```
        var googleCredentials = GoogleCredentials.create(new AccessToken(accessToken, expire));
        var storage= StorageOptions.newBuilder().setCredentials(googleCredentials).setProjectId(PROJECT_ID).build().getService();
        var blobId = BlobId.of(BUCKET_NAME, file);
        var blob = storage.get(blobId); // <= OK

        try (CloudStorageFileSystem fs = CloudStorageFileSystem.forBucket(BUCKET_NAME)) {
            Path gcsPath = fs.getPath(file);
            List<String> lines = Files.readAllLines(gcsPath, StandardCharsets.UTF_8); // <= throws com.google.cloud.storage.StorageException: Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.

        }
```

And the stacktrace
```
com.google.cloud.storage.StorageException: Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:227)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.get(HttpStorageRpc.java:437)
	at com.google.cloud.storage.StorageImpl$5.call(StorageImpl.java:315)
	at com.google.cloud.storage.StorageImpl$5.call(StorageImpl.java:312)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:311)
	at com.google.cloud.storage.contrib.nio.CloudStorageReadChannel.fetchSize(CloudStorageReadChannel.java:232)
	at com.google.cloud.storage.contrib.nio.CloudStorageReadChannel.<init>(CloudStorageReadChannel.java:110)
	at com.google.cloud.storage.contrib.nio.CloudStorageReadChannel.create(CloudStorageReadChannel.java:90)
	at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.newReadChannel(CloudStorageFileSystemProvider.java:390)
	at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.newByteChannel(CloudStorageFileSystemProvider.java:305)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.newInputStream(CloudStorageFileSystemProvider.java:482)
	at java.base/java.nio.file.Files.newInputStream(Files.java:156)
	at java.base/java.nio.file.Files.newBufferedReader(Files.java:2839)
	at java.base/java.nio.file.Files.readAllLines(Files.java:3330)
	at com.orange.khiops.service.filesystem.GCSFileService.downloadFile(GCSFileService.java:178)
	at com.orange.khiops.service.filesystem.FileSystemService.downloadFile(FileSystemService.java:80)
	at com.orange.khiops.server.grpc.service.FileExplorerGrpcServiceImpl.downloadFile(FileExplorerGrpcServiceImpl.java:217)
	at com.orange.khiops.proto.kaas.FileExplorerGrpc$MethodHandlers.invoke(FileExplorerGrpc.java:928)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:180)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at com.orange.khiops.server.grpc.LoggingInterceptor$1.onHalfClose(LoggingInterceptor.java:32)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at com.orange.khiops.server.grpc.GlobalExceptionHandlingInterceptor$1.onHalfClose(GlobalExceptionHandlingInterceptor.java:46)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 401 Unauthorized
GET https://storage.googleapis.com/storage/v1/b/kaas-di-test-storage/o/Adult%2Fresults%2Ftest.txt?fields=bucket,name,generation,size&projection=full
{
  "code" : 401,
  "errors" : [ {
    "domain" : "global",
    "location" : "Authorization",
    "locationType" : "header",
    "message" : "Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.",
    "reason" : "required"
  } ],
  "message" : "Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object."
}
```

**Comment by BenWhitehead** [comment]
Hey @wayglem, 

It looks like the `StorageOptions` you're configuring are actually being used, so the defaults are.

Try using this other `forBucket` method

```java
    try (CloudStorageFileSystem fs = CloudStorageFileSystem.forBucket(bucket, CloudStorageConfiguration.DEFAULT, options)) {
         // ...
    }
```

That will at least wire through your configured Credentials instance.
